name: Deploy to Cloudflare

on:
  push:
    branches:    
      - master

env:
  NODE_VERSION: '14.x'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install dependencies
      uses: pnpm/action-setup@v1.2.0
      with:
        version: 5.4.11
        run_install: |
          - recursive: true
            args: [--frozen-lockfile]
    - name: Build
      run: pnpm build
    - name: Deploy to Cloudflare
      uses: cloudflare/wrangler-action@1.2.0
      env:
        CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
      with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
